fixing unused installs

diff --git a/ansible/init.yaml b/ansible/init.yaml
--- a/ansible/init.yaml
+++ b/ansible/init.yaml
@@ -1,27 +1,34 @@
 ---
-- name: 'provision macos hosts'
+- name: 'provision macos hosts.ini'
   hosts: 'macos'
   tasks:
     - name: 'install homebrew'
-      shell: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
-    
+      shell: |
+        if ! command -v brew >/dev/null 2>&1
+        then
+            echo "brew not found. installing now"
+            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+        fi
+
     - name: 'install casks'
-      brew_cask:
-        state: present
+      community.general.homebrew_cask:
+        state: latest
         update_homebrew: true
         name:
           - balenaetcher
-          - iterm2
-          - mactex-no-gui
           - vagrant
-          - virtualbox
           - vlc
           - wireshark
+          # - virtualbox
+          # - iterm2
+          # - spotify
+          # - slack
+          # - mactex-no-gui
+
     - name: 'install formulae'
-      brew:
-        state: present
+      community.general.homebrew:
+        state: latest
         update_homebrew: true
-        sudo_password: "{{ ansible_become_pass }}"
         name:
           - btop
           - docker
@@ -39,13 +46,11 @@
           - ncdu
           - nmap
           - openconnect
-          - andoc
-          - owerlevel10k
+          - pandoc
           - proxychains-ng
           - pygments
           - reattach-to-user-namespace
           - rich-cli
-          - speedtest
           - sshuttle
           - tmux
           - wakeonlan
